# Generated by Django 4.1.4 on 2022-12-08 07:28

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(help_text='Введите имя и фамилию мастера', max_length=100, verbose_name='Имя и фамилия мастера')),
                ('telegram_id', models.IntegerField(verbose_name='Телеграм-ID мастера')),
                ('speciality', models.CharField(help_text='Введите специальность', max_length=1000, verbose_name='Специальность мастера')),
                ('saloon', models.CharField(help_text='Салон в котором работает мастер', max_length=1000, verbose_name='Салон')),
            ],
            options={
                'verbose_name': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(verbose_name='Телеграм-ID клиента')),
                ('fullname', models.CharField(help_text='Введите имя и фамилию клиента', max_length=100, verbose_name='Имя и фамилия клиента')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region=None, verbose_name='Номер клиента')),
            ],
            options={
                'verbose_name': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Saloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(help_text='Адрес где находится салон', verbose_name='Адрес салона')),
                ('masters', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saloons', to='timetable.master', verbose_name='Мастер')),
            ],
        ),
    ]
