# Generated by Django 4.1.4 on 2022-12-08 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AlterModelOptions(
            name='saloon',
            options={'verbose_name': 'Салон', 'verbose_name_plural': 'Салоны'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AlterField(
            model_name='saloon',
            name='address',
            field=models.CharField(help_text='Адрес где находится салон', max_length=200, verbose_name='Адрес салона'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('price', models.IntegerField(verbose_name='Цена услуги')),
                ('date', models.DateField(help_text='Дата записи', verbose_name='Дата записи')),
                ('time', models.TimeField(help_text='Время записи', verbose_name='Время записи')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='timetable.master', verbose_name='Мастер')),
                ('saloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.saloon', verbose_name='Салон')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
