# Generated by Django 4.1.4 on 2022-12-09 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_master_options_alter_saloon_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AddField(
            model_name='saloon',
            name='services',
            field=models.CharField(choices=[(0, 'Парикмахерские услуги'), (1, 'Ногтевой сервис'), (2, 'Макияж')], default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saloon',
            name='masters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saloons', to='timetable.master', verbose_name='Мастер'),
        ),
    ]
