# Generated by Django 4.1.4 on 2022-12-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_master_options_alter_saloon_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AddField(
            model_name='saloon',
            name='lat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='saloon',
            name='lon',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='saloon',
            name='title',
            field=models.CharField(default='Salon X', max_length=256, verbose_name='Имя салона'),
            preserve_default=False,
        ),
    ]
