# Generated by Django 4.1.4 on 2022-12-10 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_alter_user_options_saloon_lat_saloon_lon_and_more'),
        ('timetable', '0003_alter_user_options_saloon_services_and_more'),
    ]

    operations = [
    ]
