# Generated by Django 4.1.4 on 2022-12-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_merge_20221210_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saloon',
            name='services',
        ),
    ]
