# Generated by Django 4.1.4 on 2022-12-11 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_remove_saloon_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='speciality',
        ),
    ]
