# Generated by Django 4.1.4 on 2022-12-11 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_master_speciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите тип услуги', max_length=100, verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.RemoveField(
            model_name='master',
            name='saloon',
        ),
        migrations.AlterField(
            model_name='master',
            name='speciality',
            field=models.ForeignKey(help_text='Введите специальность', on_delete=django.db.models.deletion.CASCADE, related_name='Services', to='timetable.servicetype', verbose_name='Специальность мастера'),
        ),
    ]
