# Generated by Django 4.1.4 on 2022-12-11 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_servicetype_remove_master_saloon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Типы услуг'},
        ),
        migrations.RemoveField(
            model_name='saloon',
            name='masters',
        ),
        migrations.AddField(
            model_name='master',
            name='saloon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masters', to='timetable.saloon', verbose_name='Салон'),
        ),
        migrations.AlterField(
            model_name='master',
            name='telegram_id',
            field=models.IntegerField(unique=True, verbose_name='Телеграм-ID мастера'),
        ),
    ]
