# Generated by Django 4.1.4 on 2022-12-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_alter_servicetype_options_remove_saloon_masters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('Payed', 'Оплачен'), ('Done', 'Выполнен'), ('Cancel', 'Отменен')], default='', max_length=200),
            preserve_default=False,
        ),
    ]
