# Generated by Django 4.1.4 on 2022-12-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='saloon',
            name='master',
            field=models.ManyToManyField(related_name='saloons', to='timetable.master', verbose_name='Мастера в салоне'),
        ),
    ]
