# Generated by Django 4.1.4 on 2022-12-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_alter_master_saloon_alter_saloon_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AddField(
            model_name='servicetype',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена услуги'),
            preserve_default=False,
        ),
    ]
